#!/usr/bin/env node
/**
 * Pre-flight checks. Run `npm run verify` before deploying.
 *
 * Every check here exists because something actually went wrong once. The output is
 * meant to be read by a person, not parsed: each failure says what is wrong, where,
 * and what to do about it.
 *
 * Exit code 0 = safe to deploy. Anything else = do not push.
 *
 * Flags:
 *   --no-build   skip the rebuild and check the existing dist/ (faster, use with care)
 */

import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, statSync, existsSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');

// ─── repo configuration ──────────────────────────────────────────────────────

const CONFIG = {
  name: 'Tuesday Night Arguing',

  /** Folders under src/ that are generated by sync-publish and must NOT be tracked. */
  generatedPaths: ['src/content/chapters/', 'public/illustrations/', 'src/lib/build-info.ts'],

  /** Source files that must be tracked even though they sit in a generated folder. */
  mustBeTracked: ['src/content/config.ts', 'astro.config.mjs', 'netlify.toml', 'package.json'],

  /** Assets: warn above the first, fail above the second. */
  warnBytes: 2 * 1024 * 1024,
  failBytes: 8 * 1024 * 1024,

  /** Nothing yet — this repo starts clean, and it would be good to keep it that way. */
  allowLarge: [],

  allowBrokenLinks: [],

  rules: [
    {
      name: 'No content from the kids\' book has leaked in',
      scanDist: true,
      // 'twelve and up' is allowed: the About page describes the other book on purpose.
      pattern: /Thorn Axehand|Nibbles McPicklepants|Derek the dwarf cleric/i,
      fix: 'This is the adult telling. Shared world facts belong in EthiumSource, not copied here.',
    },
    {
      name: 'No DM material in a public novel repo',
      scan: ['publish'],
      pattern: /DM Secret|DM \/ author only|Do not put this in published/i,
      fix: 'Spoilers belong in the private EthiumSource repo. This site has no password.',
    },
  ],
};

// ─── plumbing ────────────────────────────────────────────────────────────────

const results = [];
let hardFail = false;

function pass(title, detail = '') { results.push({ level: 'PASS', title, detail, items: [] }); }
function warn(title, items, fix = '') { results.push({ level: 'WARN', title, detail: fix, items }); }
function fail(title, items, fix = '') { hardFail = true; results.push({ level: 'FAIL', title, detail: fix, items }); }

function git(cmd) {
  return execSync(`git ${cmd}`, { cwd: root, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
}

async function walk(dir, out = []) {
  let entries;
  try { entries = await readdir(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === 'node_modules' || e.name === '.git') continue;
      await walk(full, out);
    } else out.push(full);
  }
  return out;
}

const rel = (p) => path.relative(root, p).split(path.sep).join('/');
const allowed = (p, list) => list.some((a) => (a.endsWith('/') ? p.startsWith(a) : p === a));

// ─── 1. everything the build needs is committed ──────────────────────────────

function checkTracked() {
  const tracked = new Set(git('ls-files').split('\n').filter(Boolean));
  const missing = [];

  for (const required of CONFIG.mustBeTracked) {
    if (existsSync(path.join(root, required)) && !tracked.has(required)) {
      missing.push(`${required} — on disk but NOT committed`);
    }
  }

  // Anything under src/ or scripts/ that git is ignoring, other than generated output.
  const ignored = git('ls-files --others --ignored --exclude-standard -- src scripts')
    .split('\n')
    .filter(Boolean)
    .filter((f) => !CONFIG.generatedPaths.some((g) => f.startsWith(g)));

  for (const f of ignored) missing.push(`${f} — ignored by .gitignore but lives in source`);

  if (missing.length) {
    fail('Files the build needs are not in the repo', missing,
      'Netlify clones the repo, not your folder. Add a negation to .gitignore and `git add -f` the file. This is exactly how the Oct 2026 deploy broke.');
  } else {
    pass('Everything the build needs is committed');
  }
}

// ─── 2. broken links and images ──────────────────────────────────────────────

async function checkLinks() {
  const pages = (await walk(dist)).filter((f) => f.endsWith('.html'));
  if (!pages.length) { fail('No pages were built', [], 'Run the build first.'); return; }

  const exists = (route) => {
    const clean = decodeURIComponent(route.split('#')[0].split('?')[0]);
    if (!clean.startsWith('/')) return null;
    const p = path.join(dist, clean);
    return existsSync(p) || existsSync(path.join(p, 'index.html'));
  };

  const badLinks = new Set();
  const badImages = new Set();

  for (const page of pages) {
    const html = readFileSync(page, 'utf8');
    const from = '/' + rel(page).replace(/^dist\//, '').replace(/index\.html$/, '');
    for (const m of html.matchAll(/href="([^"]+)"/g)) {
      const href = m[1];
      if (/^(https?:|#|mailto:|tel:|data:)/.test(href)) continue;
      if (exists(href) === false && !CONFIG.allowBrokenLinks.includes(href)) {
        badLinks.add(`${from}  →  ${href}`);
      }
    }
    for (const m of html.matchAll(/<img[^>]+src="([^"]+)"/g)) {
      const src = m[1];
      if (/^(https?:|data:)/.test(src)) continue;
      if (exists(src) === false) badImages.add(`${from}  →  ${src}`);
    }
  }

  if (badLinks.size) fail('Broken internal links', [...badLinks], 'The page on the left links to something that was not built.');
  else pass(`No broken links (${pages.length} pages crawled)`);

  if (badImages.size) fail('Broken images', [...badImages], 'Check the filename, and that the map is listed in table-assets/table-maps.manifest.');
  else pass('No broken images');
}

// ─── 3. asset weight and duplicates ──────────────────────────────────────────

async function checkAssets() {
  const files = (await walk(path.join(root, 'publish'))).map((f) => ({ path: rel(f), size: statSync(f).size }));

  const tooBig = files.filter((f) => f.size > CONFIG.failBytes && !allowed(f.path, CONFIG.allowLarge));
  const heavy = files.filter((f) => f.size > CONFIG.warnBytes && f.size <= CONFIG.failBytes);

  const mb = (n) => `${(n / 1048576).toFixed(1)}MB`;

  if (tooBig.length) {
    fail('Files over the size limit', tooBig.map((f) => `${mb(f.size)}  ${f.path}`),
      `Over ${mb(CONFIG.failBytes)}. Re-export it smaller, or add it to allowLarge in scripts/verify.mjs with a reason.`);
  } else {
    pass('No oversized files');
  }

  if (heavy.length) {
    warn(`${heavy.length} file(s) over ${mb(CONFIG.warnBytes)}`, heavy.slice(0, 12).map((f) => `${mb(f.size)}  ${f.path}`),
      'Not blocking. Worth re-exporting if any of these are novel plates rather than DM maps.');
  }

  // byte-identical duplicates
  const bySize = new Map();
  for (const f of files) {
    if (f.size < 64 * 1024) continue;
    (bySize.get(f.size) ?? bySize.set(f.size, []).get(f.size)).push(f);
  }
  const dupes = [];
  for (const group of bySize.values()) {
    if (group.length < 2) continue;
    const byHash = new Map();
    for (const f of group) {
      const h = createHash('md5').update(readFileSync(path.join(root, f.path))).digest('hex');
      if (byHash.has(h)) dupes.push(`${mb(f.size)}  ${f.path}\n            is identical to  ${byHash.get(h)}`);
      else byHash.set(h, f.path);
    }
  }
  if (dupes.length) warn(`${dupes.length} duplicate file(s)`, dupes, 'Same bytes stored twice. 160MB of these were removed in Oct 2026.');
  else pass('No duplicate files');
}

// ─── 4. naming ───────────────────────────────────────────────────────────────

async function checkNaming() {
  const files = (await walk(path.join(root, 'publish'))).map(rel);
  const offenders = files.filter((f) => {
    const base = path.basename(f);
    return / /.test(base) || /[^\x20-\x7e]/.test(base) || /\.[A-Z]+$/.test(base);
  });
  if (offenders.length) {
    warn(`${offenders.length} file(s) with awkward names`, offenders.slice(0, 15),
      'Spaces, capitals in extensions and invisible characters break shell commands and sync scripts. A non-breaking space in one filename defeated a delete in Oct 2026. Prefer kebab-case.');
  } else {
    pass('Filenames are shell-safe');
  }
}

// ─── 5. secrets ──────────────────────────────────────────────────────────────

function checkSecrets() {
  const patterns = [
    [/sk-[A-Za-z0-9]{20,}/, 'an OpenAI-style API key'],
    [/PUBLIC_[A-Z_]*(PASSKEY|PASSWORD|SECRET|TOKEN)\s*=\s*\S+/, 'a PUBLIC_ secret (these are compiled into the browser bundle)'],
    [/(password|passkey)\s*[:=]\s*['"][^'"]{6,}['"]/i, 'a hard-coded password'],
  ];
  const tracked = git('ls-files').split('\n').filter(Boolean)
    .filter((f) => /\.(ts|js|mjs|astro|json|md|example|toml|ya?ml)$/.test(f));

  const hits = [];
  for (const f of tracked) {
    if (f === 'scripts/verify.mjs') continue;
    if ((CONFIG.allowSecrets ?? []).includes(f)) continue;
    let text;
    try { text = readFileSync(path.join(root, f), 'utf8'); } catch { continue; }
    for (const [re, what] of patterns) {
      const m = text.match(re);
      if (m) hits.push(`${f} — looks like ${what}: ${m[0].slice(0, 48)}`);
    }
  }
  if (hits.length) fail('Possible secret committed', hits, 'Move it to a Netlify environment variable. Anything PUBLIC_ prefixed is served to every visitor.');
  else pass('No secrets found in tracked files');
}

// ─── 6. repo-specific rules ──────────────────────────────────────────────────

async function checkRules() {
  const distPages = (await walk(dist)).filter((f) => f.endsWith('.html'));

  for (const rule of CONFIG.rules) {
    if (rule.scan) {
      const files = [];
      for (const dir of rule.scan) files.push(...(await walk(path.join(root, dir))));
      const hits = [];
      for (const f of files.filter((f) => f.endsWith('.md'))) {
        const lines = (await readFile(f, 'utf8')).split('\n');
        lines.forEach((line, i) => {
          if (!rule.pattern.test(line)) return;
          if (rule.ignore && rule.ignore.test(line)) return;
          hits.push(`${rel(f)}:${i + 1}  ${line.trim().slice(0, 90)}`);
        });
      }
      const report = rule.level === 'warn' ? warn : fail;
      hits.length ? report(rule.name, hits.slice(0, 20), rule.fix + (hits.length > 20 ? ` (${hits.length} total)` : '')) : pass(rule.name);
    }

    if (rule.scanDist) {
      const hits = distPages.filter((f) => rule.pattern.test(readFileSync(f, 'utf8'))).map(rel);
      hits.length ? fail(rule.name, hits, rule.fix) : pass(rule.name);
    }

    if (rule.fileMustContain) {
      const p = path.join(root, rule.fileMustContain.file);
      const ok = existsSync(p) && rule.fileMustContain.pattern.test(readFileSync(p, 'utf8'));
      ok ? pass(rule.name) : fail(rule.name, [rule.fileMustContain.file], rule.fix);
    }

    if (rule.distEveryPageContains) {
      const missing = distPages.filter((f) => !rule.distEveryPageContains.test(readFileSync(f, 'utf8'))).map(rel);
      missing.length ? fail(rule.name, missing, rule.fix) : pass(rule.name);
    }
  }
}

// ─── run ─────────────────────────────────────────────────────────────────────

const colour = process.stdout.isTTY;
const tint = (c, s) => (colour ? `\u001b[${c}m${s}\u001b[0m` : s);

async function main() {
  console.log(`\nVerifying ${CONFIG.name}\n${'─'.repeat(60)}`);

  if (!process.argv.includes('--no-build')) {
    console.log('Building…');
    try {
      execSync('npm run build', { cwd: root, stdio: 'pipe' });
      pass('Build succeeded');
    } catch (error) {
      hardFail = true;
      const out = (error.stdout?.toString() ?? '') + (error.stderr?.toString() ?? '');
      fail('Build failed', out.split('\n').filter((l) => /error|Error|✗/.test(l)).slice(0, 12),
        'Fix the build before anything else — nothing below can be trusted.');
    }
  }

  checkTracked();
  checkSecrets();
  if (existsSync(dist)) {
    await checkLinks();
    await checkRules();
  }
  await checkAssets();
  await checkNaming();

  console.log('');
  for (const r of results) {
    const badge = r.level === 'PASS' ? tint(32, ' PASS ') : r.level === 'WARN' ? tint(33, ' WARN ') : tint(31, ' FAIL ');
    console.log(`${badge} ${r.title}`);
    for (const item of r.items) console.log(`         ${item}`);
    if (r.detail && r.level !== 'PASS') console.log(`         ${tint(90, '→ ' + r.detail)}`);
  }

  const failed = results.filter((r) => r.level === 'FAIL').length;
  const warned = results.filter((r) => r.level === 'WARN').length;
  console.log('\n' + '─'.repeat(60));
  if (hardFail) {
    console.log(tint(31, `${failed} check(s) failed. Do not deploy.`) + (warned ? ` (${warned} warning(s))` : ''));
    process.exit(1);
  }
  console.log(tint(32, 'All checks passed.') + (warned ? ` ${warned} warning(s) above — not blocking.` : ''));
}

main().catch((error) => { console.error(error); process.exit(1); });
